### ISSUE TITLE
Catalogue form need to be on frontend

### ISSUE THREAD

**Issue by Grazulex** [Grazulex/cetronic#21]
The user that will used the catalogue fonction is not admin and need to managed this in the frontend

**Comment by Grazulex** [comment]
We can maybe try to play with the rôle to show only this fonction in the backend menu for a special role

**Comment by PixelParty** [comment]
Yes we can install module https://v2.filamentphp.com/plugins/althinect-spatie-roles-permissions and then will use spatie roles for separate functionality

**Comment by Grazulex** [comment]
Please, wait....i need a confirmation of the customer
